### ISSUE TITLE
AtCoderで学ぶPythonの進捗管理

### ISSUE THREAD

**Issue by gariryo3** [gariryo3/ojt-code#1]
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%81%AF%E3%81%98%E3%82%81%E3%81%AB" class="">はじめに</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%9C%AC%E8%A8%98%E4%BA%8B%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6" class="">本記事について</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%9B%AE%E7%9A%84" class="">目的</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A0%85" class="focus">注意事項</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%A7%8B%E6%88%90">構成</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3--%E8%A8%80%E8%AA%9E">バージョン / 言語</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB">コーディングスタイル</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%82%B3%E3%83%BC%E3%83%89">コード</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%8F%82%E8%80%83">参考</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%9C%80%E5%BE%8C%E3%81%AB">最後に</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%AC%AC1%E7%AB%A0-%E5%85%A5%E5%87%BA%E5%8A%9B%E5%87%A6%E7%90%86">第1章 入出力処理</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#11-%E5%87%BA%E5%8A%9B">1.1 出力</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%95%B4%E6%95%B0int">整数（int）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%B5%AE%E5%8B%95%E5%B0%8F%E6%95%B0%E7%82%B9%E6%95%B0float">浮動小数点数（float）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97str">文字列（str）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%83%AA%E3%82%B9%E3%83%88list">リスト（list）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%8C%BA%E5%88%87%E3%82%8A%E6%96%87%E5%AD%97%E3%81%AE%E6%8C%87%E5%AE%9A">区切り文字の指定</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%9C%AB%E5%B0%BE%E6%96%87%E5%AD%97%E3%81%AE%E6%8C%87%E5%AE%9A">末尾文字の指定</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#12-%E5%85%A5%E5%8A%9B">1.2 入力</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#1%E8%A1%8C--1%E5%88%97">1行 / 1列</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#1%E8%A1%8C--%E8%A4%87%E6%95%B0%E5%88%97">1行 / 複数列</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A4%87%E6%95%B0%E8%A1%8C--1%E5%88%97">複数行 / 1列</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A4%87%E6%95%B0%E8%A1%8C--%E8%A4%87%E6%95%B0%E5%88%97">複数行 / 複数列</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%AC%AC2%E7%AB%A0-%E6%BC%94%E7%AE%97">第2章 演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#21-%E7%AE%97%E8%A1%93%E6%BC%94%E7%AE%97">2.1 算術演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%8A%A0%E7%AE%97">加算</a>
- [x] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%B8%9B%E7%AE%97">減算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E4%B9%97%E7%AE%97">乗算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E9%9A%8E%E4%B9%97">階乗</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%81%B9%E3%81%8D%E4%B9%97">べき乗</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%81%B9%E3%81%8D%E6%A0%B9">べき根</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E9%99%A4%E7%AE%97">除算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%B0%8F%E6%95%B0%E7%82%B9%E5%88%87%E3%82%8A%E6%8D%A8%E3%81%A6%E9%99%A4%E7%AE%97">小数点切り捨て除算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%B0%8F%E6%95%B0%E7%82%B9%E5%88%87%E3%82%8A%E4%B8%8A%E3%81%92%E9%99%A4%E7%AE%97">小数点切り上げ除算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E5%89%B0%E4%BD%99">剰余</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#22-%E8%AB%96%E7%90%86%E6%BC%94%E7%AE%97">2.2 論理演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#23-%E6%AF%94%E8%BC%83%E6%BC%94%E7%AE%97">2.3 比較演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%AC%AC3%E7%AB%A0-%E5%88%B6%E5%BE%A1%E6%A7%8B%E6%96%87">第3章 制御構文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#31-%E6%9D%A1%E4%BB%B6%E6%96%87">3.1 条件文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#if%E6%96%87">if文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#in%E6%BC%94%E7%AE%97">in演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E4%B8%89%E9%A0%85%E6%BC%94%E7%AE%97">三項演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#in%E6%BC%94%E7%AE%97-1">in演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A4%87%E6%95%B0%E6%9D%A1%E4%BB%B6%E5%BC%8F">複数条件式</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#32-%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E6%96%87">3.2 繰り返し文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#for%E6%96%87">for文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#range%E9%96%A2%E6%95%B0">range関数</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#in%E6%BC%94%E7%AE%97-2">in演算</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#while%E6%96%87">while文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%AC%AC4%E7%AB%A0-%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BF%E5%9E%8B">第4章 組み込み型</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#41-%E6%95%B4%E6%95%B0int">4.1 整数（int）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#42-%E6%96%87%E5%AD%97%E5%88%97str">4.2 文字列（str）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E5%AE%9A%E7%BE%A9">文字列の定義</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E9%80%A3%E7%B5%90">文字列の連結</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97">文字列の繰り返し</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E5%8F%82%E7%85%A7">文字列の参照</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E6%AF%94%E8%BC%83">文字列の比較</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E9%80%86%E9%A0%86">文字列の逆順</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E5%87%BA%E7%8F%BE%E5%9B%9E%E6%95%B0">文字列の出現回数</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%96%87%E5%AD%97%E5%88%97%E3%81%AE%E7%BD%AE%E6%8F%9B">文字列の置換</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%82%B9%E3%83%A9%E3%82%A4%E3%82%B9">スライス</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#43-%E3%83%AA%E3%82%B9%E3%83%88list">4.3 リスト（list）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E5%8F%82%E7%85%A7">要素の参照</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E8%BF%BD%E5%8A%A0">要素の追加</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E6%8E%A2%E7%B4%A2">要素の探索</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E5%8F%96%E3%82%8A%E5%87%BA%E3%81%97">要素の取り出し</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E5%8F%96%E3%82%8A%E9%99%A4%E3%81%8D">要素の取り除き</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E5%89%8A%E9%99%A4">要素の削除</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E5%87%BA%E7%8F%BE%E5%9B%9E%E6%95%B0">要素の出現回数</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E7%B5%90%E5%90%88">要素の結合</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E8%A6%81%E7%B4%A0%E3%81%AE%E3%83%A6%E3%83%8B%E3%83%BC%E3%82%AF%E5%8C%96">要素のユニーク化</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%82%B9%E3%83%A9%E3%82%A4%E3%82%B9-1">スライス</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%AC%AC5%E7%AB%A0-%E7%B5%84%E3%81%BF%E8%BE%BC%E3%81%BF%E9%96%A2%E6%95%B0">第5章 組み込み関数</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#51-%E9%95%B7%E3%81%95len">5.1 長さ（len）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#52-%E3%82%BD%E3%83%BC%E3%83%88sorted">5.2 ソート（sorted）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%98%87%E9%A0%86">昇順</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E9%99%8D%E9%A0%86">降順</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#53-%E6%9C%80%E5%A4%A7%E5%80%A4max">5.3 最大値（max）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#54-%E6%9C%80%E5%B0%8F%E5%80%A4min">5.4 最小値（min）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#55-%E5%90%88%E8%A8%88%E5%80%A4sum">5.5 合計値（sum）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%95%B0%E5%AD%97%E5%92%8C">数字和</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#56-%E7%B5%B6%E5%AF%BE%E5%80%A4abs">5.6 絶対値（abs）</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E4%BB%98%E9%8C%B2">付録</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E4%BB%A3%E5%85%A5%E6%96%87">代入文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E7%B4%AF%E7%AE%97%E4%BB%A3%E5%85%A5%E6%96%87">累算代入文</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E6%BC%94%E7%AE%97%E5%AD%90%E3%81%AE%E5%84%AA%E5%85%88%E9%A0%86%E4%BD%8D">演算子の優先順位</a>
- [ ] <a href="https://qiita.com/KoyanagiHitoshi/items/3286fbc65d56dd67737c#%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E5%9E%8B%E3%82%92%E7%A2%BA%E8%AA%8D%E3%81%99%E3%82%8B">オブジェクトの型を確認する</a>
